# version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_back
    ports:
      - "5432:5434"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
